In [1]:
import numpy as np

In [2]:
Gx = np.array([
        [1, 0, -1],
        [2, 0, -2],
        [1, 0, -1]
    ])

In [3]:
Gy = np.array([
        [-1, -2, -1],
        [0, 0, 0],
        [1, 2, 1]
    ])

In [17]:
temp = np.array([
        [1, 1, 1],
        [1, 1, 1],
        [2, 3, 3]
    ])

In [18]:
np.absolute(Gy*temp).sum()

15

In [19]:
num_rows = 5
num_cols = 6

In [21]:
seams = []

In [22]:
i = 1
for r in range(num_rows):
    temp_row = []
    for c in range(num_cols):
        temp_row.append(i)
        i+=1
    seams.append(temp_row)

In [23]:
seams

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12],
 [13, 14, 15, 16, 17, 18],
 [19, 20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29, 30]]

In [24]:
seams[0]

[1, 2, 3, 4, 5, 6]

In [26]:
seams[0][:]

[1, 2, 3, 4, 5, 6]

In [27]:
 [[  9. 225.   0.   9.   9.   8.]
 [  9.   1. 225.   8.   9.   8.]
 [  9.   9.   0. 225.   0.   8.]
 [  9.   9.   9. 225. 225.   8.]
 [  9.   9. 225.   0. 225.   8.]]


SyntaxError: invalid syntax (<ipython-input-27-2263afe500cd>, line 1)

In [28]:
a = [1,2,3,4]

In [29]:
a[:0]

[]

In [30]:
a[1:]

[2, 3, 4]

In [31]:
a.pop(0)

1

In [32]:
a

[2, 3, 4]

In [34]:
a = [2, 4, 1]
b = sorted(a)
a, b

([2, 4, 1], [1, 2, 4])

In [35]:
c = enumerate(a)
c

In [36]:
for part in c:
    print(part)

(0, 2)
(1, 4)
(2, 1)


In [38]:
c.length()

AttributeError: 'enumerate' object has no attribute 'length'

In [41]:
d = List(c)
len(d)

NameError: name 'List' is not defined

In [40]:
d

[]

In [43]:
import pandas as pd

ModuleNotFoundError: No module named 'pandas'

In [ ]:
def get_tweets_from_user(user_id):
    """ Opens a csv files of many tweets from many users and returns only tweets from user_id."""
    
    return tweets

In [42]:
def has_tweeted_user_id(user_id, tweets):
    """Returns true/false if a user has tweeted a user_id.
    
    Parameters:
        user_id (Int): This is the Twitter user id number for a given user.
        tweets (DataFrame): subset of tweets in (dataset.csv) from user with id user_id
    
    Returns:
        (Boolean): true if user_id has tweeted a different user's id in tweets.
    """
    
    # for user_id, go through tweets and see if another user_id is present. Return true if found. Otherwise false.
    
    return result

In [ ]:
def calculate_information_gain(data):
    """ """
    return i_gain

In [ ]:
list_of_user_ids = pd.DataFrame()